name: minimax
description: A new Flutter project.

publish_to: 'none'

version: 0.100.31+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.0
  flutter_svg: ^1.0.0
  flutter_secure_storage: ^5.0.2
  package_info: ^2.0.2
  dio: ^4.0.0
  dart_rss: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_html: ^3.0.0-alpha.1
  url_launcher: ^6.0.17
  intl: ^0.17.0
  advance_pdf_viewer: ^2.0.0
  sprintf: ^6.0.0
  flutter_keyboard_visibility: ^5.1.0
  package_info_plus: ^1.3.0
  app_settings: ^4.1.1
  clipboard: ^0.1.3
  flutter_share: ^2.0.0
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^11.2.10
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.1.4
  quiver: ^3.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/backgrounds/

  fonts:
    - family: roboto
      fonts:
        - asset: fonts/roboto/Roboto-Medium.ttf
          weight: 500
    - family: roboto-mono
      fonts:
        - asset: fonts/roboto-mono/roboto-mono-300.ttf
          weight: 300
    - family: manrope
      fonts:
        - asset: fonts/manrope/manrope-extra-light.ttf
          weight: 200
        - asset: fonts/manrope/manrope-light.ttf
          weight: 300
        - asset: fonts/manrope/manrope-regular.ttf
          weight: 400
        - asset: fonts/manrope/manrope-medium.ttf
          weight: 500
        - asset: fonts/manrope/manrope-semibold.ttf
          weight: 600
        - asset: fonts/manrope/manrope-bold.ttf
          weight: 700
        - asset: fonts/manrope/manrope-extrabold.ttf
          weight: 800