name: minimax
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.0
  flutter_svg: ^1.0.0
  flutter_secure_storage: ^5.0.2
  package_info: ^2.0.2
  dio: ^4.0.0
  dart_rss: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  flutter_html: ^3.0.0-alpha.1
  url_launcher: ^6.0.17
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mocktail: ^0.1.4
  quiver: ^3.0.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/backgrounds/

  fonts:
    - family: manrope
      fonts:
        - asset: fonts/manrope/manrope-extra-light.ttf
          weight: 200
        - asset: fonts/manrope/manrope-light.ttf
          weight: 300
        - asset: fonts/manrope/manrope-regular.ttf
          weight: 400
        - asset: fonts/manrope/manrope-medium.ttf
          weight: 500
        - asset: fonts/manrope/manrope-semibold.ttf
          weight: 600
        - asset: fonts/manrope/manrope-bold.ttf
          weight: 700
        - asset: fonts/manrope/manrope-extrabold.ttf
          weight: 800